[project]
name = "python-fp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "termcolor>=3.1.0",
    "toolz>=1.0.0",
]
